Mongodb connected with express and running, eslint airbnb style imple…
redacademy/quupe-spring-2018 pull request #46
Opened 2018-06-12 22:49 UTC by 2lives

…mented.

2018-06-12 23:07 UTC, 10thfloor requested changes

2018-06-12 23:07 UTC, 10thfloor commented on quupe-server/.babelrc
> +    "presets": ["latest", "stage-2"]
Use "preset env" instead of latest & stage-2

2018-06-12 23:07 UTC, 10thfloor commented on quupe-server/src/api/schema.js
> +// const typeDefs = `{
Remove commented code.

2018-06-12 23:07 UTC, 10thfloor commented on quupe-server/src/index.js
> +var db = mongoose.connection;
Don't use "var"

2018-06-13 16:26 UTC, siddharthparmar7 requested changes
Nice work. Please make the changes so I can approve this pull request.

2018-06-13 16:26 UTC, siddharthparmar7 commented on quupe-server/src/api/resolvers.js
> +            return items.map(x => {
X is not a good variable name. Change it to item.

2018-06-13 16:26 UTC, siddharthparmar7 commented on quupe-server/src/index.js
> +let db = mongoose.connection;
change this let to const since you are not going to change your DB connection.

2018-06-13 16:26 UTC, siddharthparmar7 commented on quupe-server/src/index.js
> +const PORT = 3333;
add code that allows a PORT number to be either 3333 or take settings from the env variables.

2018-06-13 18:17 UTC, closed without merging

2018-06-13 18:18 UTC, siddharthparmar7 commented
Changing path to GraphCool