Created placeholder filter for borrow, adds react-native-elements pac…
redacademy/quupe-spring-2018 pull request #59
Opened 2018-06-13 23:37 UTC by EricChan277

…kage, removes firebase from podfile, adds maps

2018-06-14 08:21 UTC, EricChan277 commented
I have remade this branch with placeholder view for map for now, have not removed firebase or added maps to podfile.

2018-06-18 17:44 UTC, siddharthparmar7 requested changes
Nice work! Please make the requested changes.

2018-06-18 17:44 UTC, siddharthparmar7 commented on quupe-RN/js/components/Map/Map.js
> +  console.log(location.longitude);
please remove this console logs.

2018-06-18 17:44 UTC, siddharthparmar7 commented on quupe-RN/js/components/Map/Map.js
> +
please add prop-types for location.

2018-06-18 17:44 UTC, siddharthparmar7 commented on quupe-RN/js/screens/Borrow/BorrowContainer.js
> +    this.state = {
we are going to move this (state info) to either Redux or to the server soon (not with this pull request).

2018-06-18 17:44 UTC, siddharthparmar7 commented on quupe-RN/package.json
>          "react-native-firebase": "^4.2.0",
Please remove firebase from here.

2018-06-18 17:44 UTC, siddharthparmar7 commented on quupe-RN/android/app/src/main/java/com/quupe/MainApplication.java
> +            new VectorIconsPackage()
I think rebasing is not done properly because Realm is still part your project, please put it back through rebasing. Otherwise, really good work.

2018-06-18 20:47 UTC, siddharthparmar7 approved these changes
Thank you!

2018-06-18 20:48 UTC, merged